version: '3'

services:
  app:
    image: node:18
    container_name: node_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && node server.js"
