name: CI/CD for Node.js App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Set up environment variables
        run: echo "IMAGE_NAME=sandwhydev/my-node-app" >> $GITHUB_ENV # ✅ Pakai username Docker Hub

      - name: Logout from Docker Hub (prevent conflicts)
        run: docker logout

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Debug IMAGE_NAME
        run: echo "IMAGE_NAME=${{ env.IMAGE_NAME }}"

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest .
          docker push ${{ env.IMAGE_NAME }}:latest
