name: CI/CD for Node.js App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests (Opsional)
        run: echo "No tests yet"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }} & ${{ secrets.DOCKER_USERNAME }}"

      - name: Push Docker Image
        run: |
          docker tag my-node-app mydockerhubusername/my-node-app:latest
          docker push mydockerhubusername/my-node-app:latest

      - name: Run Docker Container
        run: docker run -d -p 3000:3000 my-node-app
